import React, { useEffect, useState } from 'react';

export const euler2 = () => {
  const [displayFibonacci, setDisplayFibonacci] = useState([]);
  const [displaySum, setDisplaySum] = useState(0);

  useEffect(() => {
    let fibonacci = [];
    let previous = 0;
    let current = 1;
    let next = previous + current;
      while (next < 4000000) {
        if (next % 2 == 0) {
          fibonacci.push(next);
        }
        previous = current;
        current = next;
        next = previous + current;
      }
    
    console.log(fibonacci);
    setDisplayFibonacci(fibonacci);
    let sum = 0;
    fibonacci.forEach(num => {
      sum += num;
    });
    setDisplaySum(sum);
  }, []);

  return (
    <>
      <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
      <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

      <br />
      <div className="display-equation">{displayFibonacci.map(num => <span key={num}>{num}{displayFibonacci.indexOf(num) + 1 < displayFibonacci.length ? " + " : " = "}</span>)}</div>
      <h3><span className="spoiler">{displaySum}</span></h3>
    </>
  );
};

export default euler2;