import React, { useEffect, useState } from 'react';

export const euler2 = () => {
  const [displayFibonacci, setDisplayFibonacci] = useState([]);

  useEffect(() => {
    let fibonacci = [];
    let previous = 0;
    let current = 1;
    for (let i = 0; i < 10; i++) {
      var next = previous + current;
      fibonacci.push(next)
      previous = current;
      current = next;
    }
    console.log(fibonacci);
    setDisplayFibonacci(fibonacci);
  }, []);

  return (
    <>
      <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
      <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

      <br />
      <div className="display-equation">{displayFibonacci}</div>
      <h3><span className="spoiler"></span></h3>
    </>
  );
};

export default euler2;